# Generated by Django 4.2.6 on 2024-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
