# Generated by Django 4.2.6 on 2024-05-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses_app", "0002_course_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
